export { gaussianBlur } from './blur'
export * from './color'
export { compositeOverBackground, type CompositorOptions } from './compositor'
export { computeSignedDetail, extractLuminance, resolveDetailRadius, splitDetail } from './high-pass'
export { applyMorphology, dilate, erode } from './morphology'
export { generateOpaqueTexture } from './opaque-texture'
export { runExtraction, SlabExtractionPipeline } from './pipeline'
export { cloneConfig, DEFAULT_CONFIG, mergeConfig, TED_WILLIAMS_FRONT_PRESET } from './presets'
export { buildProtectedMask } from './protected-regions'
export { classifyPlasticLikelihood, generateTransmissionMask } from './transmission'
export type * from './types'
export { estimateScannerWhite } from './white-estimation'
